### ISSUE TITLE
[BUG] HUD does not show for token that is attached to another token via Token Attacher

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-core#107]
**Describe the bug**
The HUD is only shown for the "master token", the mount in this case. It is not shown for the attached token, the rider (a Player Character) in my case.

**Steps to reproduce**
1. Attach rider to mount via Token Attacher.
2. HUD is not shown for GM for the rider any more.

**Versions:**
- current versions of all systems and modules.

**Comment by Larkinabout** [comment]
Is there still a way to control an individual token within an attached set? I'd maybe look to a development on Token Attacher's side to allow tokens to be individually controlled. Any solution on Token Action HUD Core's side won't be optimal as it needs to know which token you actually want to control in order to grab the actions for that token/actor.

**Comment by Larkinabout** [comment]
Closing as deemed best to resolve on Token Attacher side.
