### ISSUE TITLE
[FEATURE] I have some ideas about customizing the HUD for Earthdawn 4E

### ISSUE THREAD

**Issue by MountainshadowIRL** [Larkinabout/fvtt-token-action-hud-core#131]
**Describe your idea**
I heard you guys might be looking for somebody to help with the Token Action HUD for Earthdawn. Well my Earthdawn group plays every week and I have just a really cool idea in mind...

I'm trying to get my Earthdawn tabletop to the level of polish I see in some D&D games. One version of a HUD which I have seen, called  "Argon" had a nice tray at across the bottom of the screen which incorporated icon art and made a nice looking UI for the players. But it also divided action types and made it easier for players to plan out their actions. Something similar could also support "declaration" type initiative phases, which are awesome but often impractical.

I would like to make a custom UI for Earthdawn with similar function for which I would provide really nice custom art assets.  I want to make nice looking player UI based on the Token Action HUD, and I want to...

A: Use the data from the character sheet to categorize available action buttons into Standard Actions, Simple Actions, Free Actions,  and Movement Actions.
B: Gray out combinations to help players determine what combinations of things they can try
C: Setup a "Declarations" system that has a "ready" button for players so they can lock in their declared action before initiative is rolled- Since Initiative abilities are part of the declaration for the round, they can trigger automatically with the auto initiative
D- Use art assets to setup Medkit with potions, backpack, or quiver with slots...

Token Action HUD in combination with the Earthdawn Compendiums already has most of the mechanisms in place and I can bring the art to make it look really good :)

**Versions**
- Token Action HUD System: [e.g. token-action-hud-dnd5e]
- System: [e.g. dnd5e]

**Additional context**
Any additional context.

**Comment by Larkinabout** [comment]
Hi @MountainshadowIRL, Token Action HUD Core allows other developers to build system-specific Token Action HUD modules. I'm not looking to develop a Token Action HUD Earthdawn 4e myself, but if another developer wishes to, I can provide advice on getting started.

_Argon - Combat HUD_ is a bespoke HUD tailored for D&D 5e whereas Token Action HUD Core is a generic, customisable HUD catered to any system (with the addition of a dedicated Token Action HUD system module). With some clever CSS you may be able to make it look a bit more like Argon, but it's never going to compare with a module designed for a specific system.

I'd say, if you want a more customisable version of Token Action HUD, see if you can find someone (or yourself) to develop a Token Action HUD system module using Token Action HUD Core. See [Developing a System Module](https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/Developing-a-System-Module). Otherwise, you may be looking at finding someone to develop a bespoke module like Argon.

**Comment by MountainshadowIRL** [comment]
Excellent- great to meet you. 
I am definitely interested in trying to customize the core module for Earthdawn ( and several other game systems which have specific needs. ) Now, Argon is cool... but it has a bunch of stuff that's useless to me, and is missing some things I would really like to have. Visually I was just thinking of it as inspiration. But yes I have several ideas for things I would like to (probably myself) create related to the HUD and I would appreciate any help you can offer :)

**Comment by Larkinabout** [comment]
The best way I've found to get started is to check out the [Developing a System Module](https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/Developing-a-System-Module) article and download the code for another Token Action HUD system module and just start replacing code for your system. This is a good one to use: [Token Action HUD Exalted Third Edition](https://github.com/Aliharu/token-action-hud-exaltedthird)).
