### ISSUE TITLE
[SYSTEM] Shadowdark RPG

### ISSUE THREAD

**Issue by chrpow** [Larkinabout/fvtt-token-action-hud-core#207]
**Describe your idea**
I would like to help write a module to support Shadowdark RPG (https://foundryvtt.com/packages/shadowdark)

I tried following the instructions at https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/Developing-a-System-Module but had difficulty installing the template module (I've created an issue on that repo as well).

**Comment by Larkinabout** [comment]
As mentioned on your issue here: https://github.com/Larkinabout/fvtt-token-action-hud-template/issues/3, the template code is a a placeholder for your code and cannot be installed as a module in Foundry VTT.

Token Action HUD system modules are reliant on other developers. If you have any questions, let me know.

**Comment by chrpow** [comment]
I've created a module for Shadowdark: https://github.com/chrpow/fvtt-token-action-hud-shadowdark/tree/main

This can be closed. Thanks!

**Comment by Larkinabout** [comment]
Great! Check out [Core Changes for System Module Developers](https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/Core-Changes-for-System-Module-Developers) for changes introduced in Token Action HUD Core 1.5.0. The deprecated methods will still work, but you'll get warnings in the console. You might also be interested in the `registerStyles` to add your own Shadowdark-themed HUD style.
