### ISSUE TITLE
[QUESTION] When using an ActionHandlerExtender, how do you actually handle the action?

### ISSUE THREAD

**Issue by ddbrown30** [Larkinabout/fvtt-token-action-hud-core#267]
I'm attempting to add some additional functionality to the SWADE token hud through my own module. Adding an ActionHandlerExtender seems to be the way to do this. I'm able to add my new actions to the group but there doesn't appear to be a way to actually handle the actions.

handleActionClickCore in the RollHandler only calls handleActionClick which will just call that function in the extended class. I'm not finding any method that passes the click onto the extenders.

What is the correct way to add and handle custom actions without making changes to the system module itself?

**Comment by Larkinabout** [comment]
I think it's probably an oversight generally, though it's been a long time since I've looked at that stuff and it was mostly ported over from TAH Classic.

There is functionality to add a roll handler that can be chosen by the user in the module settings via `getAvailableRollHandlers` and `getRollHandlers`, but that overrides the original roll handler entirely. TAH Core will need some development to add a roll handler extender akin to `ActionHandlerExtender`.

**Comment by ddbrown30** [comment]
Got it. I thought that might be the case. If I have some time I'll see about putting together a PR.

**Comment by ddbrown30** [comment]
I'm trying to get my dev environment set up for this and I can't get it to launch correctly. I'm guessing it's something to do with how you've configured it to use the bundled version by default. I tried switching esmodules to use `scripts/init.js` instead of `./dist/token-action-hud-core.min.js` but that didn't do it. Any help?

**Comment by ddbrown30** [comment]
@Larkinabout any help?

**Comment by Larkinabout** [comment]
`scripts/init.js` should do it. I used to do it that way before I included the source map. Also, important to note that I'm working on a bug overhaul for ApplicationV2 and a general refactor, so it might be worth looking at the ApplicationV2 branch especially when I push the next commit.
