### ISSUE TITLE
[FEATURE] Reorganize subcategory order for custom categories

### ISSUE THREAD

**Issue by MrPotatoZed** [Larkinabout/fvtt-token-action-hud-core#56]
I wouldn't call it a bug since it's pretty magical that the actions, bonus actions, etc auto-populate. However, the current order of the subcategories is a bit wonky.  The current orders are shown below:
![image](https://user-images.githubusercontent.com/85974617/218241600-0a308732-ecab-4875-b676-5f42d2b14a64.png)
![image](https://user-images.githubusercontent.com/85974617/218238481-6c3303fd-ac26-477a-899c-c212f28249c0.png)
![image](https://user-images.githubusercontent.com/85974617/218238489-493434af-bb3a-4fd0-b774-bd9f68d58f83.png)
![image](https://user-images.githubusercontent.com/85974617/218238498-c38d2475-e324-4570-8bc4-40bb69b94f80.png)

I don't think there's any one most logical way to order them but I guess I'd default to trying to go in about the same order as the character sheets in terms of handing innate, pact, cantrips, spell in order of level, etc. Ideally consumables would not be in the middle of the spells. 

Thanks again for all your work and for considering this!  

Token Action HUD Core: 1.2.1
Token Action HUD System: 5e 1.2.1
System: dnd5e 2.1.4

**Comment by Larkinabout** [comment]
This is most likely the order in which the subcategories were added as you cycled through tokens. It'll be particularly apparent for the GM. Once they're all listed, you can reorder them. It's not ideal. Eventually I'll probably store derived subcategories against the actor rather than the user, so each actor will have its own list instead of the user getting every derived subcategory for every token they've clicked on.

**Comment by MrPotatoZed** [comment]
That's amazing; I had no idea you could right click on the subcategories to order stuff within them. Auto-magical ordering would be fine but this totally works. Thank you!

**Comment by Larkinabout** [comment]
Added #58 for specific festure development.
