### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by arcanjl** [Larkinabout/fvtt-token-action-hud-core#6]
Whenever dragging a token around sound, it broadcasts the sound of where it left, not where it went. Example, I have a token next to a fire, and I hear nothing. That is because I dragged it from an area that was too far to hear it. Now if I drag it back to that spot, I will hear the fire. Reason is that it is sending the sound of the LAST spot we were in. :)

**Comment by Larkinabout** [comment]
Hi @arcanjl, my immediate thought is this would not be affected by Token Action HUD as it does nothing with movement or position in relation to other elements on the canvas.

However, would you please disable all other modules and see if the issue is still there with Token Action HUD either enabled and disabled.

**Comment by arcanjl** [comment]
I am sorry, I should have mentioned that. Of course, I have had all mods off, except for this one. It was strange for me too...
That being said, I turned it back on just now to record it for you, and it is working perfectly. So ignore the man behind the curtain please :)
