### ISSUE TITLE
[FEATURE] Undelete categories without resetting the hud

### ISSUE THREAD

**Issue by dmrickey** [Larkinabout/fvtt-token-action-hud-core#79]
It would be nice if TAH knew which categories were hidden, and gave the option of un-hiding those options without resetting everything else that's been done.

here's a really rough html edit to give an idea of what I mean.
![image](https://user-images.githubusercontent.com/3664822/229365024-d751fb31-cdfd-4154-9c2b-32a9994c1d46.png)

Remove the 'x' buttons from the deleted categories, and allow us to move those back up to the top. Maybe instead of "Deleted Categories" call it "Hidden Categories"

**Comment by Larkinabout** [comment]
This would only be applicable if the default layout were assumed to be the expected layout, however as soon as a user customises their HUD, the default is no longer valid. Considering the functionality is there to add and remove groups at will and with ease, I don't feel this is necessary.

However, it would be useful to see actions that are added to a preset group by the TAH system module but are hidden by the user as these are hidden rather than deleted to avoid them being reshown each time the HUD is updated. These are different from actions that are added manually by the user to a group outside of where the TAH system module adds them.

The ideal solution would be to show a shown/hidden icon instead of an X on the action tags in the list and allow it to be toggled, but this would likely require messing with the tagify code. A solution similar to your screenshot would likely be the best alternative.

**Comment by Larkinabout** [comment]
The layout of the dialogs was changed in Token Action HUD Core 1.4.12 to make it easier to add and remove items as per the above screenshot. I'm going to count this as resolving this request as although it doesn't show the system's default groups specifically, it does make adding any group very easy.
