### ISSUE TITLE
[BUG] Resetting HUD seems to leave behind some flags

### ISSUE THREAD

**Issue by dmrickey** [Larkinabout/fvtt-token-action-hud-core#92]
In PF1 I've got some settings that organize some things in different ways. E.g. for skills I basically have "just show all skills lumped together" or "categorize skills". The categorize option lumps all knowledge skills together (and some other groupings). However with the new "actions can go anywhere" feature in 1.3, it looks like it's being saved that an action was in the category, so it gets stuck there. So if that setting is swapped back and forth, then those knowledge skills end up showing in both places. 

I would expect resetting the HUD to clear out those skills and then only show them in whatever the setting is currently toggled to, but it doesn't, and those skills are stuck in both places as long as a skill with that ID is being built.

I've worked around it by giving each skill a unique id depending on which way the setting is toggled, but it seems like Core is missing something when resetting that should be taken care of.

**Versions:**
- Token Action HUD Core: [e.g. 1.3.1]
- System: [pf1]
- Foundry VTT: [e.g. 10.291]

**Additional context**
Any additional context.

**Comment by Larkinabout** [comment]
Probably need a way to force a subcategory and its actions to be deleted, so you can then add the subcategory based on the setting.

Alternative is to make them available as different subcategories and allow the user to choose from the dialog, rather than make it a setting. This is what I've done for D&D 5e with Abilities, Checks and Saves, where Abilities is the combination of Checks and Saves.

I'll look at adding in a delete subcategory function anyway as resetting the whole HUD to change a subcategory isn't ideal.
